site_name: Curso Angular Básico
repo_url: 'https://github.com/marcosalpereira/curso-angular-spring-boot'
docs_dir: 'docs'
site_url: 'https://marcosalpereira.github.io/curso-angular-spring-boot/'
site_dir: 'site'
theme:
  name: 'material'
  custom_dir: 'theme'
extra_css:
    - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - footnotes
  - codehilite(linenums=true)
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.details
  - markdown.extensions.attr_list
pages:
  - 'Home': 'index.md'
  - 'Exercícios':
    - '01 - Instalação': 'exercicios/exercicio-01.md'
    - '02 - Primeira Aplicação Angular': 'exercicios/exercicio-02.md'
    - '03 - Componentes, Diretivas e Serviços': 'exercicios/exercicio-03.md'
